"""partition sensor_data by time

Revision ID: 0003_partition_sensor_data
Revises: 0002_auth_audit_device
Create Date: 2026-03-17 00:00:00
"""
from __future__ import annotations

from alembic import op

revision = "0003_partition_sensor_data"
down_revision = "0002_auth_audit_device"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE sensor_data RENAME TO sensor_data_legacy")

    op.execute(
        """
        CREATE TABLE sensor_data (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            session_id UUID NOT NULL REFERENCES sessions(id),
            timestamp TIMESTAMPTZ NOT NULL,
            gsr DOUBLE PRECISION NOT NULL,
            heart_rate INTEGER NOT NULL,
            temperature DOUBLE PRECISION NOT NULL,
            blood_pressure_sys INTEGER NOT NULL,
            blood_pressure_dia INTEGER NOT NULL,
            PRIMARY KEY (id, timestamp)
        ) PARTITION BY RANGE (timestamp)
        """
    )

    op.execute(
        """
        DO $$
        DECLARE
            start_date date := date_trunc('month', now())::date;
            end_date date := (date_trunc('month', now()) + interval '1 month')::date;
            part_name text := 'sensor_data_' || to_char(start_date,'YYYY_MM');
        BEGIN
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS %I PARTITION OF sensor_data FOR VALUES FROM (%L) TO (%L)',
                part_name, start_date, end_date
            );
        END $$;
        """
    )

    op.execute("CREATE TABLE sensor_data_default PARTITION OF sensor_data DEFAULT")

    op.execute(
        """
        INSERT INTO sensor_data (id, session_id, timestamp, gsr, heart_rate, temperature, blood_pressure_sys, blood_pressure_dia)
        SELECT id, session_id, timestamp, gsr, heart_rate, temperature, blood_pressure_sys, blood_pressure_dia
        FROM sensor_data_legacy
        """
    )

    op.execute("DROP TABLE sensor_data_legacy")

    op.execute("CREATE INDEX ix_sensor_data_session_id ON sensor_data (session_id)")
    op.execute("CREATE INDEX ix_sensor_data_timestamp ON sensor_data (timestamp)")
    op.execute("CREATE INDEX ix_sensor_data_session_timestamp ON sensor_data (session_id, timestamp)")


def downgrade() -> None:
    op.execute("DROP TABLE sensor_data_default")
    op.execute("DROP TABLE sensor_data CASCADE")
